# Generated by Django 4.2.1 on 2023-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, null=True)),
                ('lastname', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('password', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='voter',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
