# Generated by Django 4.2.1 on 2023-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0002_candidate_rename_name_voter_firstname_voter_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('no_of_seats', models.IntegerField(default=1)),
            ],
        ),
    ]
