# Generated by Django 4.2.1 on 2023-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0004_remove_candidate_password_candidate_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
    ]
