# Generated by Django 4.2.1 on 2023-05-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0005_alter_voter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voted',
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.IntegerField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.IntegerField(max_length=11, null=True, unique=True),
        ),
    ]
