# Generated by Django 4.2.1 on 2023-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0006_remove_voter_voted_candidate_phone_alter_voter_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='photo',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
