# Generated by Django 4.2.1 on 2023-05-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0008_voter_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='photo',
        ),
    ]
