# Generated by Django 4.2.1 on 2023-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0013_candidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
