# Generated by Django 4.2.1 on 2023-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0014_voter_is_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='no_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
