# Generated by Django 4.2.1 on 2023-05-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0015_candidate_no_of_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
